### ISSUE TITLE
XML-RPC urlopen error [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by actonsys** [OCA/odoorpc#61] opened 2021-06-03 19:18 UTC
Trying to connect Odoo 13 in production mode (reverse proxy nginx active) via external API XML-RPC and getting the following error:

urlopen error [Errno 101] Network is unreachable

**Comment by pedrobaeza** [comment] 2021-06-03 19:20
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot and they are accessible through XML-RPC (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Closed by pedrobaeza** 2021-06-03 19:20 UTC

**Comment by actonsys** [comment] 2021-06-03 19:29
Hi Pedro. http://runbot.odoo.com/runbot is running via reverse proxy as well?

**Comment by pedrobaeza** [comment] 2021-06-03 19:31
I don't know, but the question is that the problem is not on Odoo code, for which this tracker serves, it's in your deployment, so you have to check that, and use other tool (forum for example), for exchanging questions and ideas.

**Comment by actonsys** [comment] 2021-06-05 06:43
For whom came across to the same issue, I sorted this out changing odoo.conf (Odoo 13 in production mode, reverse proxy nginx active) as follows:
http_interface = 0.0.0.0
# (it was 127.0.0.1)
Using 127.0.0.1 allows only access via xml-rpc internally in the same ambient, setting url to '127.0.0.1', but with http_interface = 0.0.0.0 is possible to access externally normally setting url to ip_address.
Thanks.
